name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check
        run: |
          sudo apt install gettext
          python3 check-po-files.py
          ./check-merge.sh
